github_owner       = "geraldakenji"
github_repo        = "geraldakenji/artistAPI"
github_branch      = "master"
github_token       = ""
role_name          = "devops-role"
ecr_repository_url = "269629789070.dkr.ecr.us-east-1.amazonaws.com/devops-demo"